### ISSUE TITLE
MPTCPanalyzer installation issue

### ISSUE THREAD

**Issue by vidyakubde** [teto/pymptcpanalyzer#34]
* mptcpanalyzer version (`$ mptcpanalyzer --version` or commit number):mptcpanalyzer 0.3.2
* tshark version (`$ tshark --version`, must be >= 3.X.X):Wireshark 3.2.2 
* python version (`$ python --version`, must be >= 3.7):Python 3.7.7

Output of mptcpanalyzer -dDEBUG (or -dTRACE ):
```python3.5 -mpip install mptcpanalyzer --user
Collecting mptcpanalyzer
  Using cached mptcpanalyzer-0.3.2-py3-none-any.whl (95 kB)
Collecting cmd2>=0.9.15
  Using cached cmd2-1.0.2-py3-none-any.whl (111 kB)
Collecting stevedore
  Using cached stevedore-1.32.0-py2.py3-none-any.whl (43 kB)
ERROR: Could not find a version that satisfies the requirement pandas>=0.25 (from mptcpanalyzer) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas>=0.25 (from mptcpanalyzer)
	HERE
```

#

**Comment by teto** [comment]
thanks for the report. There is a development version that is currently broken (due to the transition wtih pandas > 1.), I will try to fix it asap. What do you want to use mptcpanalyzer for ?

**Comment by vidyakubde** [comment]
Hi,
Thanks for the reply, I am trying to study some of the MPTCP schedulers,
experimentation is already done . I have used SS comand for analysis of the
result.
But wanted to track the results with mptcpanlyzer also.    Mostly how much
time will it take.


Thanks

**Comment by teto** [comment]
I've pushed some changes to the `next` branch. Commands that use 2 pcaps (to compute one way delays for instance) are still buggy. I will try to fix them today.

**Comment by teto** [comment]
I fixed the tests, let me know if everything works fine. If it does, I will prepare a new release.

**Comment by vidyakubde** [comment]
ok sir, will check and inform you
 thanks

**Comment by vidyakubde** [comment]
hello sir
 The issue is still not resolved, again the same error

Thanks






vidya@ubuntu:~$ python3 -mpip install mptcpanalyzer --user
Collecting mptcpanalyzer
  Using cached mptcpanalyzer-0.3.2-py3-none-any.whl (95 kB)
Collecting matplotlib>=3.0.3
  Using cached matplotlib-3.0.3-cp35-cp35m-manylinux1_x86_64.whl (13.0 MB)
Collecting cmd2>=0.9.15
  Using cached cmd2-1.0.2-py3-none-any.whl (111 kB)
Collecting stevedore
  Using cached stevedore-1.32.0-py2.py3-none-any.whl (43 kB)
ERROR: Could not find a version that satisfies the requirement pandas>=0.25
(from mptcpanalyzer) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0,
0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1,
0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1,
0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0,
0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1,
0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2,
0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1,
0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas>=0.25 (from mptcpanalyzer)
WARNING: You are using pip version 20.1; however, version 20.1.1 is
available.
You should consider upgrading via the '/usr/bin/python3 -m pip install
--upgrade pip' command.

**Comment by teto** [comment]
I meant try the development version, I've added instructions how to do it in
https://github.com/teto/mptcpanalyzer#installation

**Comment by vidyakubde** [comment]
ok sir, will see to it and update you

**Comment by vidyakubde** [comment]
Hello sir,

sudo git clone git@github.com:teto/mptcpanalyzer.git
Cloning into 'mptcpanalyzer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by teto** [comment]
I fixed the url in the README, one should use `https://github.com/teto/mptcpanalyzer.git`. 
Also you should not use sudo it will mess up your file permissions.

**Comment by vidyakubde** [comment]
Hello sir
I tried development version, it worked . But there was issue in

python3 setup.py develop command
vidya@ubuntu:~/mptcpanalyzer$ sudo python3  setup.py develop
running develop
running egg_info
writing dependency_links to mptcpanalyzer.egg-info/dependency_links.txt
writing mptcpanalyzer.egg-info/PKG-INFO
writing entry points to mptcpanalyzer.egg-info/entry_points.txt
writing top-level names to mptcpanalyzer.egg-info/top_level.txt
writing requirements to mptcpanalyzer.egg-info/requires.txt
reading manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.5/dist-packages/mptcpanalyzer.egg-link
(link to .)
mptcpanalyzer 0.3.2 is already the active version in easy-install.pth
Installing mptcpanalyzer script to /usr/local/bin

Installed /home/vidya/mptcpanalyzer
Processing dependencies for mptcpanalyzer==0.3.2
Searching for pandas>=1.0
Reading https://pypi.org/simple/pandas/
Downloading https://files.pythonhosted.org/packages/2f/79/f236ab1cfde94bac03d7b58f3f2ab0b1cc71d6a8bda3b25ce370a9fe4ab1/pandas-1.0.3.tar.gz#sha256=32f42e322fb903d0e189a4c10b75ba70d90958cc4f66a1781ed027f1a1d14586
Best match: pandas 1.0.3
Processing pandas-1.0.3.tar.gz
Writing /tmp/easy_install-o1nr50dg/pandas-1.0.3/setup.cfg
Running pandas-1.0.3/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-o1nr50dg/pandas-1.0.3/egg-dist-tmp-fdcqlvu4
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-o1nr50dg/pandas-1.0.3/setup.py", line 42
    f"numpy >= {min_numpy_ver}",
                              ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    zip_safe=False,
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/develop.py",
line 38, in run
    self.install_for_development()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/develop.py",
line 156, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py",
line 765, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py",
line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py",
line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py",
line 1078, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py",
line 692, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py",
line 718, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py",
line 903, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py",
line 1171, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py",
line 1157, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 253, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/_vendor/six.py",
line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py",
line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-o1nr50dg/pandas-1.0.3/setup.py", line 42
    f"numpy >= {min_numpy_ver}",
                              ^
SyntaxError: invalid syntax
vidya@ubuntu:~/mptcpanalyzer$

**Comment by teto** [comment]
sry for delay, I thought I had answered already :s 
pandas use `f-strings`, a feature introduced in python 3.6. Mptcpanalyzer itself requires python3.7 (as stated in README.md). I will see if I can add a check in setup.py.

**Comment by vidyakubde** [comment]
Thanks sir, I tried by using Python3.7, but it is giving me the same error.
Waiting for ur response

**Comment by teto** [comment]
it can't give you the same error twice as you changed python version, the paths at least should be different, please copy the backtrace. I've pushed a ppython version check on master too if you want to update your clone.

**Comment by vidyakubde** [comment]
I have updated the clone, and tried, this is what i am getting
vidya@ubuntu:~/mptcpanalyzer$ sudo python3.7 setup.py develop
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'long_description_content_type'
  warnings.warn(msg)
running develop
Checking .pth file support in /usr/local/lib/python3.7/dist-packages/
/usr/bin/python3.7 -E -c pass
TEST PASSED: /usr/local/lib/python3.7/dist-packages/ appears to support
.pth files
running egg_info
writing mptcpanalyzer.egg-info/PKG-INFO
writing dependency_links to mptcpanalyzer.egg-info/dependency_links.txt
writing entry points to mptcpanalyzer.egg-info/entry_points.txt
writing requirements to mptcpanalyzer.egg-info/requires.txt
writing top-level names to mptcpanalyzer.egg-info/top_level.txt
reading manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.7/dist-packages/mptcpanalyzer.egg-link
(link to .)
mptcpanalyzer 0.3.2 is already the active version in easy-install.pth
Installing mptcpanalyzer script to /usr/local/bin

Installed /home/vidya/mptcpanalyzer
Processing dependencies for mptcpanalyzer==0.3.2
Searching for jsonschema
Reading https://pypi.python.org/simple/jsonschema/
Best match: jsonschema 3.2.0
Downloading
https://files.pythonhosted.org/packages/69/11/a69e2a3c01b324a77d3a7c0570faa372e8448b666300c4117a516f8b1212/jsonschema-3.2.0.tar.gz#sha256=c8a85b28d377cc7737e46e2d9f2b4f44ee3c0e1deac6bf46ddefc7187d30797a
Processing jsonschema-3.2.0.tar.gz
Writing /tmp/easy_install-go11slpz/jsonschema-3.2.0/setup.cfg
Running jsonschema-3.2.0/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-go11slpz/jsonschema-3.2.0/egg-dist-tmp-8lr62hk9
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'use_scm_version'
  warnings.warn(msg)
warning: install_lib: 'build/lib' does not exist -- no Python modules to
install

zip_safe flag not set; analyzing archive contents...
Removing /usr/local/lib/python3.7/dist-packages/UNKNOWN-0.0.0-py3.7.egg
Moving UNKNOWN-0.0.0-py3.7.egg to /usr/local/lib/python3.7/dist-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/dist-packages/UNKNOWN-0.0.0-py3.7.egg
error: The 'jsonschema' distribution was not found and is required by
mptcpanalyzer

**Comment by teto** [comment]
I've removed jsonschema from the dependencies on master. Could you try again ?

**Comment by vidyakubde** [comment]
I tried again with the master, but still the same error


sudo python3.7 setup.py develop
[sudo] password for vidya:
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'long_description_content_type'
  warnings.warn(msg)
running develop
Checking .pth file support in /usr/local/lib/python3.7/dist-packages/
/usr/bin/python3.7 -E -c pass
TEST PASSED: /usr/local/lib/python3.7/dist-packages/ appears to support
.pth files
running egg_info
creating mptcpanalyzer.egg-info
writing mptcpanalyzer.egg-info/PKG-INFO
writing dependency_links to mptcpanalyzer.egg-info/dependency_links.txt
writing entry points to mptcpanalyzer.egg-info/entry_points.txt
writing requirements to mptcpanalyzer.egg-info/requires.txt
writing top-level names to mptcpanalyzer.egg-info/top_level.txt
writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
reading manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.7/dist-packages/mptcpanalyzer.egg-link
(link to .)
mptcpanalyzer 0.3.2 is already the active version in easy-install.pth
Installing mptcpanalyzer script to /usr/local/bin

Installed /home/vidya/mptcpanalyzer
Processing dependencies for mptcpanalyzer==0.3.2
Searching for jsonschema
Reading https://pypi.python.org/simple/jsonschema/
Best match: jsonschema 3.2.0
Downloading
https://files.pythonhosted.org/packages/69/11/a69e2a3c01b324a77d3a7c0570faa372e8448b666300c4117a516f8b1212/jsonschema-3.2.0.tar.gz#sha256=c8a85b28d377cc7737e46e2d9f2b4f44ee3c0e1deac6bf46ddefc7187d30797a
Processing jsonschema-3.2.0.tar.gz
Writing /tmp/easy_install-suzhh0cu/jsonschema-3.2.0/setup.cfg
Running jsonschema-3.2.0/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-suzhh0cu/jsonschema-3.2.0/egg-dist-tmp-f69oeo6y
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'use_scm_version'
  warnings.warn(msg)
warning: install_lib: 'build/lib' does not exist -- no Python modules to
install

zip_safe flag not set; analyzing archive contents...
Removing /usr/local/lib/python3.7/dist-packages/UNKNOWN-0.0.0-py3.7.egg
Moving UNKNOWN-0.0.0-py3.7.egg to /usr/local/lib/python3.7/dist-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/dist-packages/UNKNOWN-0.0.0-py3.7.egg
error: The 'jsonschema' distribution was not found and is required by
mptcpanalyzer

**Comment by teto** [comment]
are you sure you are testing with https://github.com/teto/mptcpanalyzer/commit/e038d56c3127b53346e2424e4bc356d4b8c0b9d4 ?

**Comment by vidyakubde** [comment]
Hello sir,
   I tried with the new version, infact i reinstalled python 3.7.7 also






vidya@ubuntu:~$ git clone https://github.com/teto/mptcpanalyzer.git
Cloning into 'mptcpanalyzer'...
remote: Enumerating objects: 577, done.
remote: Counting objects: 100% (577/577), done.
remote: Compressing objects: 100% (220/220), done.
remote: Total 3709 (delta 425), reused 489 (delta 356), pack-reused 3132
Receiving objects: 100% (3709/3709), 22.25 MiB | 933.00 KiB/s, done.
Resolving deltas: 100% (2861/2861), done.
Checking connectivity... done.
Checking out files: 100% (137/137), done.
vidya@ubuntu:~$ cd mptcpanalyzer
vidya@ubuntu:~/mptcpanalyzer$ sudo python3.7 setup.py develop
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'long_description_content_type'
  warnings.warn(msg)
running develop
Checking .pth file support in /usr/local/lib/python3.7/dist-packages/
/usr/bin/python3.7 -E -c pass
TEST PASSED: /usr/local/lib/python3.7/dist-packages/ appears to support
.pth files
running egg_info
creating mptcpanalyzer.egg-info
writing mptcpanalyzer.egg-info/PKG-INFO
writing dependency_links to mptcpanalyzer.egg-info/dependency_links.txt
writing entry points to mptcpanalyzer.egg-info/entry_points.txt
writing requirements to mptcpanalyzer.egg-info/requires.txt
writing top-level names to mptcpanalyzer.egg-info/top_level.txt
writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
reading manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.7/dist-packages/mptcpanalyzer.egg-link
(link to .)
mptcpanalyzer 0.3.2 is already the active version in easy-install.pth
Installing mptcpanalyzer script to /usr/local/bin

Installed /home/vidya/mptcpanalyzer
Processing dependencies for mptcpanalyzer==0.3.2
Searching for jsonschema
Reading https://pypi.python.org/simple/jsonschema/
Best match: jsonschema 3.2.0
Downloading
https://files.pythonhosted.org/packages/69/11/a69e2a3c01b324a77d3a7c0570faa372e8448b666300c4117a516f8b1212/jsonschema-3.2.0.tar.gz#sha256=c8a85b28d377cc7737e46e2d9f2b4f44ee3c0e1deac6bf46ddefc7187d30797a
Processing jsonschema-3.2.0.tar.gz
Writing /tmp/easy_install-vp_0wfj1/jsonschema-3.2.0/setup.cfg
Running jsonschema-3.2.0/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-vp_0wfj1/jsonschema-3.2.0/egg-dist-tmp-i6kbnc8v
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution
option: 'use_scm_version'
  warnings.warn(msg)
warning: install_lib: 'build/lib' does not exist -- no Python modules to
install

zip_safe flag not set; analyzing archive contents...
Removing /usr/local/lib/python3.7/dist-packages/UNKNOWN-0.0.0-py3.7.egg
Moving UNKNOWN-0.0.0-py3.7.egg to /usr/local/lib/python3.7/dist-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/dist-packages/UNKNOWN-0.0.0-py3.7.egg
error: The 'jsonschema' distribution was not found and is required by
mptcpanalyzer

**Comment by teto** [comment]
on the CI, the python install works fine so I believe it's something on your system. Maybe try in a virtual environment ?

**Comment by vandit86** [comment]
> Python 3.8.5
> Wireshark 3.4.2 

**error during the installation from dev version --> No package 'py3cairo' found**
Any idea ?? thanks 

> vad@vad-VB:~/mptcpanalyzer$ sudo apt-get install -y python3-cairo
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-cairo is already the newest version (1.16.2-2ubuntu2).
> 0 upgraded, 0 newly installed, 0 to remove and 226 not upgraded.

**AND installation process** 

> vad@vad-VB:~/mptcpanalyzer$ sudo python3 setup.py develop
> running develop
> running egg_info
> writing mptcpanalyzer.egg-info/PKG-INFO
> writing dependency_links to mptcpanalyzer.egg-info/dependency_links.txt
> writing entry points to mptcpanalyzer.egg-info/entry_points.txt
> writing requirements to mptcpanalyzer.egg-info/requires.txt
> writing top-level names to mptcpanalyzer.egg-info/top_level.txt
> reading manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
> writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
> running build_ext
> Creating /usr/local/lib/python3.8/dist-packages/mptcpanalyzer.egg-link (link to .)
> mptcpanalyzer 0.3.4 is already the active version in easy-install.pth
> Installing mptcpanalyzer script to /usr/local/bin
> 
> Installed /home/vad/mptcpanalyzer
> Processing dependencies for mptcpanalyzer==0.3.4
> Searching for pygobject==3.36.1
> Reading https://pypi.org/simple/pygobject/
> Downloading https://files.pythonhosted.org/packages/93/41/bf9ab8929f51dac2979ae81bb094728bacee3ceb049def72d3fc1bcb4241/PyGObject-3.36.1.tar.gz#sha256=012a589aec687bfa809a1ff9f5cd775dc7f6fcec1a6bc7fe88e1002a68f8ba34
> Best match: PyGObject 3.36.1
> Processing PyGObject-3.36.1.tar.gz
> Writing /tmp/easy_install-r2l6lnop/PyGObject-3.36.1/setup.cfg
> Running PyGObject-3.36.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r2l6lnop/PyGObject-3.36.1/egg-dist-tmp-v159aia6
> Package py3cairo was not found in the pkg-config search path.
> Perhaps you should add the directory containing `py3cairo.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'py3cairo' found
> Traceback (most recent call last):
>   File "/tmp/easy_install-r2l6lnop/PyGObject-3.36.1/setup.py", line 178, in _run_pkg_config
>   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.8/subprocess.py", line 512, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '('pkg-config', '--print-errors', '--exists', 'py3cairo >= 1.11.1')' returned non-zero exit status 1.
>

**Comment by vandit86** [comment]
> > Python 3.8.5
> > Wireshark 3.4.2
> 
> **error during the installation from dev version --> No package 'py3cairo' found**
> Any idea ?? thanks
> 
> > vad@vad-VB:~/mptcpanalyzer$ sudo apt-get install -y python3-cairo
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > python3-cairo is already the newest version (1.16.2-2ubuntu2).
> > 0 upgraded, 0 newly installed, 0 to remove and 226 not upgraded.
> 
> **AND installation process**
> 
> > vad@vad-VB:~/mptcpanalyzer$ sudo python3 setup.py develop
> > running develop
> > running egg_info
> > writing mptcpanalyzer.egg-info/PKG-INFO
> > writing dependency_links to mptcpanalyzer.egg-info/dependency_links.txt
> > writing entry points to mptcpanalyzer.egg-info/entry_points.txt
> > writing requirements to mptcpanalyzer.egg-info/requires.txt
> > writing top-level names to mptcpanalyzer.egg-info/top_level.txt
> > reading manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
> > writing manifest file 'mptcpanalyzer.egg-info/SOURCES.txt'
> > running build_ext
> > Creating /usr/local/lib/python3.8/dist-packages/mptcpanalyzer.egg-link (link to .)
> > mptcpanalyzer 0.3.4 is already the active version in easy-install.pth
> > Installing mptcpanalyzer script to /usr/local/bin
> > Installed /home/vad/mptcpanalyzer
> > Processing dependencies for mptcpanalyzer==0.3.4
> > Searching for pygobject==3.36.1
> > Reading https://pypi.org/simple/pygobject/
> > Downloading https://files.pythonhosted.org/packages/93/41/bf9ab8929f51dac2979ae81bb094728bacee3ceb049def72d3fc1bcb4241/PyGObject-3.36.1.tar.gz#sha256=012a589aec687bfa809a1ff9f5cd775dc7f6fcec1a6bc7fe88e1002a68f8ba34
> > Best match: PyGObject 3.36.1
> > Processing PyGObject-3.36.1.tar.gz
> > Writing /tmp/easy_install-r2l6lnop/PyGObject-3.36.1/setup.cfg
> > Running PyGObject-3.36.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r2l6lnop/PyGObject-3.36.1/egg-dist-tmp-v159aia6
> > Package py3cairo was not found in the pkg-config search path.
> > Perhaps you should add the directory containing `py3cairo.pc'
> > to the PKG_CONFIG_PATH environment variable
> > No package 'py3cairo' found
> > Traceback (most recent call last):
> > File "/tmp/easy_install-r2l6lnop/PyGObject-3.36.1/setup.py", line 178, in _run_pkg_config
> > File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
> > return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> > File "/usr/lib/python3.8/subprocess.py", line 512, in run
> > raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '('pkg-config', '--print-errors', '--exists', 'py3cairo >= 1.11.1')' returned non-zero exit status 1.

**was solved with :** 

> sudo apt-get install python3-cairo-dev

**Comment by teto** [comment]
thanks for the notification, I may update the install instructions as I've switched to poetry https://python-poetry.org/ for packaging. Would you mind running a `poetry install` in a clone to see if that works correctly ?
